version: 2.1 
 
setup: << pipeline.parameters.run-setup >>

orbs:
  slack: circleci/slack@3.4.2
  path-filtering: circleci/path-filtering@0.0.2
 
parameters:
  run-setup:
    type: boolean
    default: true
  build_hypgames:
    type: boolean
    default: false

jobs:
  module-a:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: "echo 'Hello from module A!'"

  module-b:
    machine: true
    steps:
      - checkout
      - run: "echo 'Hello from module B!'"
      - run: exit 1

  module-b-post:
    docker:
      - image: alpine
    steps:
      - run: "echo 'Continuing module B!'"
      - run: env
      
  final-job:
    docker:
      - image: alpine
    steps:
      - run: echo "finished building"

workflows:
  version: 2.1
  pre:
    when: << pipeline.parameters.run-setup >>
    jobs:
      - path-filtering/filter:
          # Compare files on main
          base-revision: buildme/naga/circleorb
          # Config for continuation; herein we reuse this config itself
          config-path: .circleci/config.yml
          # 3-column space-separated table for mapping; `path-to-test parameter-to-set value-for-parameter` for each row
          mapping: |
            .* run-setup false
            module-a/.* build_hypgames true

  module-a:
    when: << pipeline.parameters.build_hypgames >>
    jobs :
      - module-a
      - module-b
      - final-job
